# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c82ea01416c2c3833c9323c719d809723cfc80476b5f9482b4b69e3a85cc54bd9b01eb7a5ae0d6ff39e1b9b005ed4067f8530b0db0c0c183266409c6a8d557ef

test:
  secret_key_base: 9b0f821eb7bd5cac00f857b0bacd86280d34de11632d0357233599fdda9bb8e02e42b22a95d20f1f6a1fec7460c2b080ab96a98da92e7d816feb0cdf871b3648

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
